import 'package:zetesis/model/material_biblioteca.dart';

abstract final class SeedMateriais {
  static const materiais = [
    MaterialBibliotecaModel(
      nome: 'O Mito de Sísifo',
      tipo: 'Textos',
      descricao:
          'O ensaio em que Camus encara o absurdo e a questão do suicídio.',
      autor: 'Albert Camus',
      dataEnvio: '12/03/2024',
      enviadoPor: 'Prof. Helena Castro',
    ),
    MaterialBibliotecaModel(
      nome: 'Discurso do Método',
      tipo: 'Textos',
      descricao: 'A dúvida metódica e o caminho até o "penso, logo existo".',
      autor: 'René Descartes',
      dataEnvio: '03/09/2023',
      enviadoPor: 'Prof. Marcos Lima',
    ),
    MaterialBibliotecaModel(
      nome: 'Carta sobre o Humanismo',
      tipo: 'Textos',
      descricao: 'Heidegger responde a Sartre sobre o sentido do humanismo.',
      autor: 'Martin Heidegger',
      dataEnvio: '28/11/2024',
      enviadoPor: 'Prof. Ana Beatriz',
    ),
    MaterialBibliotecaModel(
      nome: 'A Náusea — excerto',
      tipo: 'Textos',
      descricao: 'Trecho do romance filosófico de Sartre sobre a contingência.',
      autor: 'Jean-Paul Sartre',
      dataEnvio: '15/01/2025',
      enviadoPor: 'Prof. Helena Castro',
    ),
    MaterialBibliotecaModel(
      nome: 'Aforismos sobre o Tempo',
      tipo: 'Textos',
      descricao: 'Seleção de aforismos nietzschianos sobre eterno retorno.',
      autor: 'Friedrich Nietzsche',
      dataEnvio: '07/06/2024',
      enviadoPor: 'Prof. Rui Tavares',
    ),
    MaterialBibliotecaModel(
      nome: 'Construção',
      tipo: 'Músicas',
      descricao: 'A música de Chico Buarque como retrato da condição operária.',
      autor: 'Chico Buarque',
      dataEnvio: '22/04/2024',
      enviadoPor: 'Prof. Marcos Lima',
    ),
    MaterialBibliotecaModel(
      nome: 'Sampa',
      tipo: 'Músicas',
      descricao: 'Caetano e o estranhamento diante da cidade grande.',
      autor: 'Caetano Veloso',
      dataEnvio: '09/10/2023',
      enviadoPor: 'Prof. Ana Beatriz',
    ),
    MaterialBibliotecaModel(
      nome: 'O Tempo Não Para',
      tipo: 'Músicas',
      descricao: 'Cazuza e a urgência de viver diante da finitude.',
      autor: 'Cazuza',
      dataEnvio: '30/12/2024',
      enviadoPor: 'Prof. Helena Castro',
    ),
    MaterialBibliotecaModel(
      nome: 'Like a Rolling Stone',
      tipo: 'Músicas',
      descricao: 'A virada de Dylan e a liberdade do desenraizamento.',
      autor: 'Bob Dylan',
      dataEnvio: '18/02/2025',
      enviadoPor: 'Prof. Rui Tavares',
    ),
    MaterialBibliotecaModel(
      nome: 'Alegoria da Caverna — animação',
      tipo: 'Vídeos',
      descricao: 'Versão animada do mito da caverna de Platão.',
      autor: 'Platão',
      dataEnvio: '05/05/2024',
      enviadoPor: 'Admin Zetesis',
    ),
    MaterialBibliotecaModel(
      nome: 'Existencialismo em 10 minutos',
      tipo: 'Vídeos',
      descricao: 'Panorama rápido das ideias de Sartre, Camus e Beauvoir.',
      autor: 'Canal Filosofia',
      dataEnvio: '14/08/2024',
      enviadoPor: 'Prof. Ana Beatriz',
    ),
    MaterialBibliotecaModel(
      nome: 'Entrevista com Viktor Frankl',
      tipo: 'Vídeos',
      descricao: 'O psiquiatra fala sobre sentido e sofrimento.',
      autor: 'Viktor Frankl',
      dataEnvio: '26/01/2023',
      enviadoPor: 'Prof. Marcos Lima',
    ),
    MaterialBibliotecaModel(
      nome: 'O que é a felicidade? — aula',
      tipo: 'Vídeos',
      descricao: 'Cortella discute a busca pela vida boa.',
      autor: 'Mario Sergio Cortella',
      dataEnvio: '11/11/2024',
      enviadoPor: 'Prof. Helena Castro',
    ),
    MaterialBibliotecaModel(
      nome: 'A Persistência da Memória',
      tipo: 'Imagens',
      descricao: 'Os relógios derretidos de Dalí e a fluidez do tempo.',
      autor: 'Salvador Dalí',
      dataEnvio: '02/07/2024',
      enviadoPor: 'Prof. Rui Tavares',
    ),
    MaterialBibliotecaModel(
      nome: 'O Pensador',
      tipo: 'Imagens',
      descricao: 'A escultura de Rodin como ícone da reflexão.',
      autor: 'Auguste Rodin',
      dataEnvio: '19/03/2023',
      enviadoPor: 'Admin Zetesis',
    ),
    MaterialBibliotecaModel(
      nome: 'O Grito',
      tipo: 'Imagens',
      descricao: 'A angústia existencial pintada por Munch.',
      autor: 'Edvard Munch',
      dataEnvio: '23/09/2024',
      enviadoPor: 'Prof. Ana Beatriz',
    ),
    MaterialBibliotecaModel(
      nome: 'Caminhante sobre o Mar de Névoa',
      tipo: 'Imagens',
      descricao: 'O sublime romântico de Friedrich diante do desconhecido.',
      autor: 'Caspar David Friedrich',
      dataEnvio: '08/12/2024',
      enviadoPor: 'Prof. Marcos Lima',
    ),
    MaterialBibliotecaModel(
      nome: 'O Ser e o Nada',
      tipo: 'Livros',
      descricao: 'A obra central do existencialismo de Sartre.',
      autor: 'Jean-Paul Sartre',
      dataEnvio: '04/02/2024',
      enviadoPor: 'Prof. Helena Castro',
    ),
    MaterialBibliotecaModel(
      nome: 'Assim Falou Zaratustra',
      tipo: 'Livros',
      descricao: 'O super-homem, a morte de Deus e o eterno retorno.',
      autor: 'Friedrich Nietzsche',
      dataEnvio: '17/07/2023',
      enviadoPor: 'Prof. Rui Tavares',
    ),
    MaterialBibliotecaModel(
      nome: 'Meditações',
      tipo: 'Livros',
      descricao: 'Os escritos estoicos do imperador Marco Aurélio.',
      autor: 'Marco Aurélio',
      dataEnvio: '29/10/2024',
      enviadoPor: 'Prof. Ana Beatriz',
    ),
    MaterialBibliotecaModel(
      nome: 'A Hora da Estrela',
      tipo: 'Livros',
      descricao: 'Clarice e a existência à margem, narrada por Rodrigo S.M.',
      autor: 'Clarice Lispector',
      dataEnvio: '13/01/2025',
      enviadoPor: 'Prof. Marcos Lima',
    ),
    MaterialBibliotecaModel(
      nome: 'O Banquete',
      tipo: 'Livros',
      descricao: 'O diálogo de Platão sobre o amor e o belo.',
      autor: 'Platão',
      dataEnvio: '06/06/2023',
      enviadoPor: 'Admin Zetesis',
    ),
    MaterialBibliotecaModel(
      nome: 'Mapa mental — correntes filosóficas',
      tipo: 'Outros',
      descricao: 'Resumo visual das principais escolas, da Antiguidade a hoje.',
      autor: null,
      dataEnvio: '21/05/2024',
      enviadoPor: 'Prof. Helena Castro',
    ),
    MaterialBibliotecaModel(
      nome: 'Infográfico — linha do tempo da ética',
      tipo: 'Outros',
      descricao: 'Da ética grega ao utilitarismo numa linha do tempo.',
      autor: null,
      dataEnvio: '03/03/2025',
      enviadoPor: 'Prof. Marcos Lima',
    ),
    MaterialBibliotecaModel(
      nome: 'Podcast — Filosofia Pop #12',
      tipo: 'Outros',
      descricao: 'Episódio sobre liberdade e responsabilidade no dia a dia.',
      autor: 'Filosofia Pop',
      dataEnvio: null,
      enviadoPor: 'Prof. Rui Tavares',
    ),
    MaterialBibliotecaModel(
      nome: 'Playlist de estudo',
      tipo: 'Outros',
      descricao: 'Seleção instrumental para acompanhar as leituras.',
      autor: null,
      dataEnvio: null,
      enviadoPor: 'Admin Zetesis',
    ),
  ];
}
