// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALozDx7PKLOL74WjXd39zIu8mxtu2IWI4',
    appId: '1:557418805454:web:847f691e09587b2ab8f89f',
    messagingSenderId: '557418805454',
    projectId: 'zetesis-firebase',
    authDomain: 'zetesis-firebase.firebaseapp.com',
    storageBucket: 'zetesis-firebase.firebasestorage.app',
  );

  static const FirebaseOptions linux = web; // Sim, aponte para a web!

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0YRqMEQQvEMr6plqv4H23E22dbxD6zz4',
    appId: '1:557418805454:android:5367ccbcfa02d38ab8f89f',
    messagingSenderId: '557418805454',
    projectId: 'zetesis-firebase',
    storageBucket: 'zetesis-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPON2wHdizHn7XqluFF4KY_vLpDoVBCGU',
    appId: '1:557418805454:ios:fa54d275bbadb66cb8f89f',
    messagingSenderId: '557418805454',
    projectId: 'zetesis-firebase',
    storageBucket: 'zetesis-firebase.firebasestorage.app',
    iosBundleId: 'com.example.zetesis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPON2wHdizHn7XqluFF4KY_vLpDoVBCGU',
    appId: '1:557418805454:ios:fa54d275bbadb66cb8f89f',
    messagingSenderId: '557418805454',
    projectId: 'zetesis-firebase',
    storageBucket: 'zetesis-firebase.firebasestorage.app',
    iosBundleId: 'com.example.zetesis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALozDx7PKLOL74WjXd39zIu8mxtu2IWI4',
    appId: '1:557418805454:web:a3afc0a582fbce91b8f89f',
    messagingSenderId: '557418805454',
    projectId: 'zetesis-firebase',
    authDomain: 'zetesis-firebase.firebaseapp.com',
    storageBucket: 'zetesis-firebase.firebasestorage.app',
  );

}